Due giocatori si affrontano in una partita a dadi.
Ogni volta che un giorcatore ottiene un numero maggiore del suo revale guadagna un punto, mentre se
entrambi i giocatori ottengolo lo stesso numero, guadagnano mezzo punto ciascuno.

- Simulare una partita di 1000 lanci e rigistra i dati di 10 partite. 
- Dado truccato con maggiore probalibiltà di 5-6, ci si può accorgere ? 



In [8]:
import numpy as np


nLanci = 1000 # Per partita
puntiG1 = 0
puntiG2 = 0
p1 = 0
p2 = 0

a = np.random.randint(1,6, (10, 1000))
print(a)

[[2 3 4 ... 4 3 3]
 [3 5 1 ... 3 1 1]
 [2 2 2 ... 2 4 5]
 ...
 [2 2 1 ... 2 2 5]
 [5 2 3 ... 4 2 3]
 [5 1 5 ... 1 5 1]]


In [9]:
for line in a:
    for pos in range(len(line)-1) : 
        if line[pos] > line[pos+1]:
            puntiG1 += 1
        elif line[pos] == line[pos+1]:
            puntiG1 += 0.5
            puntiG2 += 0.5
        else:
            puntiG2 += 1
        
print (puntiG1)
print("\n")
print(puntiG2)

4982.5


5007.5


In [ ]:
import numpy as np

lanci = 1000
p1_array = np.cum